<?php
// setup our include_path
$libPaths = array(dirname(__FILE__) . '/models', '/home/robp/www/lib/php', get_include_path());
set_include_path(join(PATH_SEPARATOR, $libPaths));

// Use Zend_Loader from here on in
require_once ('Zend/Loader.php');

// not sure about using this autoloader, since it
// may prevent proper caching of generated byte code
// Zend_Loader::registerAutoload();

// load required classes
Zend_Loader::loadClass('Zend_Debug');
Zend_Loader::loadClass('Zend_Config_Xml');
Zend_Loader::loadClass('Zend_Locale');
Zend_Loader::loadClass('Zend_Locale_Format');
Zend_Loader::loadClass('Zend_Translate');
Zend_Loader::loadClass('Zend_Registry');
Zend_Loader::loadClass('Zend_Db');
Zend_Loader::loadClass('Zend_Db_Table_Abstract');
Zend_Loader::loadClass('Db_Mysql');

// get our configuration and save it in the registry
// for use by controllers
$config = new Zend_Config_Xml(dirname(__FILE__) . '/config.xml', 'staging');
Zend_Registry::set('config', $config);

// For debugging only, turn to Off for production!
ini_set('display_errors', $config->displayErrors);

// create a database object
$db = Zend_Db::factory($config->database);
Zend_Db_Table_Abstract::setDefaultAdapter($db);
